config/routes.rb
Rails.application.routes.draw do
  get 'games/new', to: 'games#new'
  post 'games/score', to: 'games#score'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    @letters = Array.new(10) { ('A'..'Z').to_a.sample }
  end

  def score
    guess = params[:guess]
    letters = params[:letters]
    if valid?(guess, letters) && english?(guess)
      @answer = "Congratulations! #{guess} is a valid English word!"
      session[:score] += guess.length
    elsif valid?(guess, letters) && !english?(guess)
      @answer = "Sorry but #{guess} does not seem to be a valid English word"
    else
      @answer = "Sorry but #{guess} can't be built out of #{letters}"
    end

    @score = session[:score]
  end

  private

  def english?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    x = JSON.parse(response.read)
    x['found'] == true
  end

  def valid?(word, list)
    word.upcase.chars.map { |x| list.include?(x) }.all?(true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<div>
  <% @letters.each do |letter| %>
    <span><%= letter %></span>
  <% end%>

  <form action="/games/score" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <label for="guess">What's the longest word you can find?</label>
    <br>
    <input type="text" id="guess" name="guess">
    <input type="hidden" name="letters" value=" <%= @letters %>">
    <input type="submit" value="Play">
  </form>
</div>

app/views/games/score.html.erb
<h1>Result</h1>


<p><%= @answer %></p>

<%= @score %>

<%= link_to 'Play again', games_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>